spring:
  redis:
    host: 101.201.154.144
    port: 6379
    password: Ssl@134679
    database: 1
    jedis:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 0
        max-wait: 1000
server:
  port: 10001

# Zookeeper客户端配置
curator:
  connectString: 127.0.0.1:2181
  retryCount: 5
  elapsedTimeMs: 5000
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000
