server:
  port: 8090

spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zep5730lmk5s5dy37o.mysql.rds.aliyuncs.com:3306/imooc-wiki-dev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    password: Ssl@199502
    username: root
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    password: Redis000
    port: 6379
#  mybatis:
#    mapper-locations:
#      - classpath:mapper/*.xml
#      - classpath*:com/**/mapper/*.xml

