server:
  port: 9001
spring:
  application:
    name: multi-datasource
  dynamic:
    baseScanPath: com.ssl.note.mapper
    defaultSource: db1
    scanType: 1
    datasource:
      db1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/seata-demo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        username: root
        password: root1234
        type: com.alibaba.druid.pool.DruidDataSource



# mybatis-plus打印sql日志
# .xml配置路径
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper-locations: classpath:mapper/*.xml